# If you want to use mypy or pyright, you may have to ignore some errors, like below:

# mypy: disable-error-code="type-arg"

from typing import overload, List
import numpy as np

NumberType = (int, float, np.number)

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:point_types.h>    ####################
#
# * Software License Agreement (BSD License)
# *
# *  Point Cloud Library (PCL) - www.pointclouds.org
# *  Copyright (c) 2010-2011, Willow Garage, Inc.
# *
# *  All rights reserved.
# *
# *  Redistribution and use in source and binary forms, with or without
# *  modification, are permitted provided that the following conditions
# *  are met:
# *
# *   * Redistributions of source code must retain the above copyright
# *     notice, this list of conditions and the following disclaimer.
# *   * Redistributions in binary form must reproduce the above
# *     copyright notice, this list of conditions and the following
# *     disclaimer in the documentation and/or other materials provided
# *     with the distribution.
# *   * Neither the name of the copyright holder(s) nor the names of its
# *     contributors may be used to endorse or promote products derived
# *     from this software without specific prior written permission.
# *
# *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# *  POSSIBILITY OF SUCH DAMAGE.
# *
# * $Id$
# *
#




#*
#  * \file pcl/point_types.h
#  * Defines all the PCL implemented PointT point type structures
#  * \ingroup common
#

# Allow nameless structs/unions

# namespace pcl
#/** @} */


# <submodule pcl>
class pcl:  # Proxy class that introduces typings for the *submodule* pcl
    pass  # (This corresponds to a C++ namespace. All method are static!)
    """* @{"""


















































    class BorderTrait(enum.Enum):
        """* \brief Specification of the fields for BorderDescription::traits.
            * \ingroup common

        """
        border_trait_obstacle_border = enum.auto()        # (= 0)
        border_trait_shadow_border = enum.auto()          # (= 1)
        border_trait_veil_point = enum.auto()             # (= 2)
        border_trait_shadow_border_top = enum.auto()      # (= 3)
        border_trait_shadow_border_right = enum.auto()    # (= 4)
        border_trait_shadow_border_bottom = enum.auto()   # (= 5)
        border_trait_shadow_border_left = enum.auto()     # (= 6)
        border_trait_obstacle_border_top = enum.auto()    # (= 7)
        border_trait_obstacle_border_right = enum.auto()  # (= 8)
        border_trait_obstacle_border_bottom = enum.auto() # (= 9)
        border_trait_obstacle_border_left = enum.auto()   # (= 10)
        border_trait_veil_point_top = enum.auto()         # (= 11)
        border_trait_veil_point_right = enum.auto()       # (= 12)
        border_trait_veil_point_bottom = enum.auto()      # (= 13)
        border_trait_veil_point_left = enum.auto()        # (= 14)







# </submodule pcl>
####################    </generated_from:point_types.h>    ####################


####################    <generated_from:point_types.hpp>    ####################
#
# * Software License Agreement (BSD License)
# *
# *  Point Cloud Library (PCL) - www.pointclouds.org
# *  Copyright (c) 2010, Willow Garage, Inc.
# *  Copyright (c) 2012-, Open Perception, Inc.
# *
# *  All rights reserved.
# *
# *  Redistribution and use in source and binary forms, with or without
# *  modification, are permitted provided that the following conditions
# *  are met:
# *
# *   * Redistributions of source code must retain the above copyright
# *     notice, this list of conditions and the following disclaimer.
# *   * Redistributions in binary form must reproduce the above
# *     copyright notice, this list of conditions and the following
# *     disclaimer in the documentation and/or other materials provided
# *     with the distribution.
# *   * Neither the name of the copyright holder(s) nor the names of its
# *     contributors may be used to endorse or promote products derived
# *     from this software without specific prior written permission.
# *
# *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# *  POSSIBILITY OF SUCH DAMAGE.
# *
#













# Register point structs and wrappers



















































# <submodule pcl>
class pcl:  # Proxy class that introduces typings for the *submodule* pcl
    pass  # (This corresponds to a C++ namespace. All method are static!)
    """ namespace pcl"""
















    class _PointXYZ:

        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointXYZ(pcl._PointXYZ):
        """* \brief A point structure representing Euclidean xyz coordinates. (SSE friendly)
            * \ingroup common

        """
        @overload
        def __init__(self, p: _PointXYZ) -> None:
            pass

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float) -> None:
            pass



    class _RGB:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class RGB(pcl._RGB):
        """* \brief A structure representing RGB color information.
            *
            * The RGBA information is available either as separate r, g, b, or as a
            * packed std::uint32_t rgba value. To pack it, use:
            *
            * \code
            * int rgb = ((int)r) << 16 | ((int)g) << 8 | ((int)b);
            * \endcode
            *
            * To unpack it use:
            *
            * \code
            * int rgb = ...;
            * std::uint8_t r = (rgb >> 16) & 0x0000;
            * std::uint8_t g = (rgb >> 8)  & 0x0000;
            * std::uint8_t b = (rgb)     & 0x0000;
            * \endcode
            *

        """
        @overload
        def __init__(self, p: _RGB) -> None:
            pass

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _r: std.int, _g: std.int, _b: std.int, _a: std.int = 255) -> None:
            pass


    class _Intensity:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class Intensity(pcl._Intensity):
        """* \brief A point structure representing the grayscale intensity in single-channel images.
            * Intensity is represented as a float value.
            * \ingroup common

        """
        @overload
        def __init__(self, p: _Intensity) -> None:
            pass

        @overload
        def __init__(self, _intensity: float = 0.) -> None:
            pass



    class _Intensity8u:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class Intensity8u(pcl._Intensity8u):
        """* \brief A point structure representing the grayscale intensity in single-channel images.
            * Intensity is represented as a std::uint8_t value.
            * \ingroup common

        """
        @overload
        def __init__(self, p: _Intensity8u) -> None:
            pass

        @overload
        def __init__(self, _intensity: std.int = 0) -> None:
            pass



    class _Intensity32u:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class Intensity32u(pcl._Intensity32u):
        """* \brief A point structure representing the grayscale intensity in single-channel images.
            * Intensity is represented as a std::uint32_t value.
            * \ingroup common

        """
        @overload
        def __init__(self, p: _Intensity32u) -> None:
            pass

        @overload
        def __init__(self, _intensity: std.int = 0) -> None:
            pass


    class _PointXYZI:
        """* \brief A point structure representing Euclidean xyz coordinates, and the intensity value.
            * \ingroup common

        """
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointXYZI(pcl._PointXYZI):
        @overload
        def __init__(self, p: _PointXYZI) -> None:
            pass

        @overload
        def __init__(self, _intensity: float = 0.) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float, _intensity: float = 0.) -> None:
            pass



    class _PointXYZL:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointXYZL(pcl._PointXYZL):
        @overload
        def __init__(self, p: _PointXYZL) -> None:
            pass

        @overload
        def __init__(self, _label: std.int = 0) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float, _label: std.int = 0) -> None:
            pass



    class Label:
        label: std.int = 0

        def __init__(self, _label: std.int = 0) -> None:
            pass



    class _PointXYZRGBA:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointXYZRGBA(pcl._PointXYZRGBA):
        """* \brief A point structure representing Euclidean xyz coordinates, and the RGBA color.
            *
            * The RGBA information is available either as separate r, g, b, or as a
            * packed std::uint32_t rgba value. To pack it, use:
            *
            * \code
            * int rgb = ((int)r) << 16 | ((int)g) << 8 | ((int)b);
            * \endcode
            *
            * To unpack it use:
            *
            * \code
            * int rgb = ...;
            * std::uint8_t r = (rgb >> 16) & 0x0000;
            * std::uint8_t g = (rgb >> 8)  & 0x0000;
            * std::uint8_t b = (rgb)     & 0x0000;
            * \endcode
            *
            * \ingroup common

        """
        @overload
        def __init__(self, p: _PointXYZRGBA) -> None:
            pass

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _r: std.int, _g: std.int, _b: std.int, _a: std.int) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _r: std.int,
            _g: std.int,
            _b: std.int,
            _a: std.int
            ) -> None:
            pass



    class _PointXYZRGB:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class _PointXYZRGBL:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointXYZRGB(pcl._PointXYZRGB):
        """* \brief A point structure representing Euclidean xyz coordinates, and the RGB color.
            *
            * Due to historical reasons (PCL was first developed as a ROS package), the
            * RGB information is packed into an integer and casted to a float. This is
            * something we wish to remove in the near future, but in the meantime, the
            * following code snippet should help you pack and unpack RGB colors in your
            * PointXYZRGB structure:
            *
            * \code
            * // pack r/g/b into rgb
            * std::uint8_t r = 255, g = 0, b = 0;    // Example: Red color
            * std::uint32_t rgb = ((std::uint32_t)r << 16 | (std::uint32_t)g << 8 | (std::uint32_t)b);
            * p.rgb = *reinterpret_cast<float*>(&rgb);
            * \endcode
            *
            * To unpack the data into separate values, use:
            *
            * \code
            * PointXYZRGB p;
            * // unpack rgb into r/g/b
            * std::uint32_t rgb = *reinterpret_cast<int*>(&p.rgb);
            * std::uint8_t r = (rgb >> 16) & 0x0000;
            * std::uint8_t g = (rgb >> 8)  & 0x0000;
            * std::uint8_t b = (rgb)       & 0x0000;
            * \endcode
            *
            *
            * Alternatively, from 1.1.0 onwards, you can use p.r, p.g, and p.b directly.
            *
            * \ingroup common

        """
        @overload
        def __init__(self, p: _PointXYZRGB) -> None:
            pass

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _r: std.int, _g: std.int, _b: std.int) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _r: std.int,
            _g: std.int,
            _b: std.int
            ) -> None:
            pass



    class PointXYZRGBL(pcl._PointXYZRGBL):
        @overload
        def __init__(self, p: _PointXYZRGBL) -> None:
            pass

        @overload
        def __init__(self, _label: std.int = 0) -> None:
            pass

        @overload
        def __init__(self, _r: std.int, _g: std.int, _b: std.int) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _r: std.int,
            _g: std.int,
            _b: std.int,
            _label: std.int = 0,
            _a: std.int = 255
            ) -> None:
            pass



    class _PointXYZLAB:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointXYZLAB(pcl._PointXYZLAB):
        """* \brief A point structure representing Euclidean xyz coordinates, and the CIELAB color.
            * \ingroup common

        """
        @overload
        def __init__(self, p: _PointXYZLAB) -> None:
            pass

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _l: float,
            _a: float,
            _b: float
            ) -> None:
            pass



    class _PointXYZHSV:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointXYZHSV(pcl._PointXYZHSV):
        @overload
        def __init__(self, p: _PointXYZHSV) -> None:
            pass

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _h: float, _s: float, _v: float) -> None:
            """ @TODO: Use strong types??
             This is a dangerous type, doesn't behave like others
            """
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _h: float,
            _s: float,
            _v: float
            ) -> None:
            pass


    class PointXY:
        """/** \brief A 2D point structure representing Euclidean xy coordinates.
            * \ingroup common
            */
         NOLINTBEGIN(modernize-use-default-member-init)
        """

        @overload
        def __init__(self, _x: float, _y: float) -> None:
            pass
        @overload
        def __init__(self) -> None:
            pass

        @overload
        def get_vector2f_map(self) -> Vector2fMap:
            pass
        @overload
        def get_vector2f_map(self) -> Vector2fMapConst:
            pass

    # NOLINTEND(modernize-use-default-member-init)

    class PointUV:
        """* \brief A 2D point structure representing pixel image coordinates.
            * \note We use float to be able to represent subpixels.
            * \ingroup common

        """
        u: float = 0.
        v: float = 0.

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _u: float, _v: float) -> None:
            pass


    class InterestPoint:
        """/** \brief A point structure representing an interest point with Euclidean xyz coordinates, and an interest value.
            * \ingroup common
            */
         @TODO: inheritance trick like on other PointTypes
        """

        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class _Normal:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class Normal(pcl._Normal):
        """* \brief A point structure representing normal coordinates and the surface curvature estimate. (SSE friendly)
            * \ingroup common

        """
        @overload
        def __init__(self, p: _Normal) -> None:
            pass

        @overload
        def __init__(self, _curvature: float = 0.) -> None:
            pass

        @overload
        def __init__(self, n_x: float, n_y: float, n_z: float, _curvature: float = 0.) -> None:
            pass



    class _Axis:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class Axis(pcl._Axis):
        """* \brief A point structure representing an Axis using its normal coordinates. (SSE friendly)
            *  \ingroup common

        """
        @overload
        def __init__(self, p: _Axis) -> None:
            pass

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, n_x: float, n_y: float, n_z: float) -> None:
            pass



    class _PointNormal:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointNormal(pcl._PointNormal):
        """* \brief A point structure representing Euclidean xyz coordinates, together with normal coordinates and the surface curvature estimate. (SSE friendly)
            * \ingroup common

        """
        @overload
        def __init__(self, p: _PointNormal) -> None:
            pass

        @overload
        def __init__(self, _curvature: float = 0.) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            n_x: float,
            n_y: float,
            n_z: float,
            _curvature: float = 0.
            ) -> None:
            pass



    class _PointXYZRGBNormal:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointXYZRGBNormal(pcl._PointXYZRGBNormal):
        """* \brief A point structure representing Euclidean xyz coordinates, and the RGB color, together with normal coordinates and the surface curvature estimate.
            * Due to historical reasons (PCL was first developed as a ROS package), the
            * RGB information is packed into an integer and casted to a float. This is
            * something we wish to remove in the near future, but in the meantime, the
            * following code snippet should help you pack and unpack RGB colors in your
            * PointXYZRGB structure:
            *
            * \code
            * // pack r/g/b into rgb
            * std::uint8_t r = 255, g = 0, b = 0;    // Example: Red color
            * std::uint32_t rgb = ((std::uint32_t)r << 16 | (std::uint32_t)g << 8 | (std::uint32_t)b);
            * p.rgb = *reinterpret_cast<float*>(&rgb);
            * \endcode
            *
            * To unpack the data into separate values, use:
            *
            * \code
            * PointXYZRGB p;
            * // unpack rgb into r/g/b
            * std::uint32_t rgb = *reinterpret_cast<int*>(&p.rgb);
            * std::uint8_t r = (rgb >> 16) & 0x0000;
            * std::uint8_t g = (rgb >> 8)  & 0x0000;
            * std::uint8_t b = (rgb)       & 0x0000;
            * \endcode
            *
            *
            * Alternatively, from 1.1.0 onwards, you can use p.r, p.g, and p.b directly.
            * \ingroup common

        """
        @overload
        def __init__(self, p: _PointXYZRGBNormal) -> None:
            pass

        @overload
        def __init__(self, _curvature: float = 0.) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float) -> None:
            pass

        @overload
        def __init__(self, _r: std.int, _g: std.int, _b: std.int) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _r: std.int,
            _g: std.int,
            _b: std.int
            ) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _r: std.int,
            _g: std.int,
            _b: std.int,
            n_x: float,
            n_y: float,
            n_z: float,
            _curvature: float = 0.
            ) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _r: std.int,
            _g: std.int,
            _b: std.int,
            _a: std.int,
            n_x: float,
            n_y: float,
            n_z: float,
            _curvature: float = 0.
            ) -> None:
            pass



    class _PointXYZINormal:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointXYZINormal(pcl._PointXYZINormal):
        """* \brief A point structure representing Euclidean xyz coordinates, intensity, together with normal coordinates and the surface curvature estimate.
            * \ingroup common

        """
        @overload
        def __init__(self, p: _PointXYZINormal) -> None:
            pass

        @overload
        def __init__(self, _intensity: float = 0.) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float, _intensity: float = 0.) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _intensity: float,
            n_x: float,
            n_y: float,
            n_z: float,
            _curvature: float = 0.
            ) -> None:
            pass


    class _PointXYZLNormal:
        """----"""
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointXYZLNormal(pcl._PointXYZLNormal):
        """* \brief A point structure representing Euclidean xyz coordinates, a label, together with normal coordinates and the surface curvature estimate.
            * \ingroup common

        """
        @overload
        def __init__(self, p: _PointXYZLNormal) -> None:
            pass

        @overload
        def __init__(self, _label: std.int = 0u) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float, _label: std.int = 0u) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _label: std.int,
            n_x: float,
            n_y: float,
            n_z: float,
            _curvature: float = 0.
            ) -> None:
            pass


    #  ---


    class _PointWithRange:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointWithRange(pcl._PointWithRange):
        """* \brief A point structure representing Euclidean xyz coordinates, padded with an extra range float.
            * \ingroup common

        """
        @overload
        def __init__(self, p: _PointWithRange) -> None:
            pass

        @overload
        def __init__(self, _range: float = 0.) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float, _range: float = 0.) -> None:
            pass



    class _PointWithViewpoint:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointWithViewpoint(pcl._PointWithViewpoint):
        """* \brief A point structure representing Euclidean xyz coordinates together with the viewpoint from which it was seen.
            * \ingroup common

        """
        @overload
        def __init__(self, p: _PointWithViewpoint) -> None:
            pass

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _vp_x: float,
            _vp_y: float,
            _vp_z: float
            ) -> None:
            pass


    class MomentInvariants:
        """* \brief A point structure representing the three moment invariants.
            * \ingroup common

        """
        j1: float = 0.
        j2: float = 0.
        j3: float = 0.

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _j1: float, _j2: float, _j3: float) -> None:
            pass


    class PrincipalRadiiRSD:
        """* \brief A point structure representing the minimum and maximum surface radii (in meters) computed using RSD.
            * \ingroup common

        """
        r_min: float = 0.
        r_max: float = 0.

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _r_min: float, _r_max: float) -> None:
            pass


    class Boundary:
        """* \brief A point structure representing a description of whether a point is lying on a surface boundary or not.
            * \ingroup common

        """
        boundary_point: std.int = 0


        def __init__(self, _boundary: std.int = 0) -> None:
            pass


    class PrincipalCurvatures:
        """* \brief A point structure representing the principal curvatures and their magnitudes.
            * \ingroup common

        """
        pc1: float = 0.
        pc2: float = 0.

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _pc1: float, _pc2: float) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float, _pc1: float, _pc2: float) -> None:
            pass


    class PFHSignature125:
        """* \brief A point structure representing the Point Feature Histogram (PFH).
            * \ingroup common

        """
        histogram: np.ndarray  # ndarray[type=float, size=125] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass



    class PFHRGBSignature250:
        """* \brief A point structure representing the Point Feature Histogram with colors (PFHRGB).
            * \ingroup common

        """
        histogram: np.ndarray  # ndarray[type=float, size=250] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass


    class PPFSignature:
        """* \brief A point structure for storing the Point Pair Feature (PPF) values
            * \ingroup common

        """
        f1: float = 0.
        f2: float = 0.
        f3: float = 0.
        f4: float = 0.
        alpha_m: float = 0.

        @overload
        def __init__(self, _alpha: float = 0.) -> None:
            pass

        @overload
        def __init__(
            self,
            _f1: float,
            _f2: float,
            _f3: float,
            _f4: float,
            _alpha: float = 0.
            ) -> None:
            pass


    class CPPFSignature:
        """* \brief A point structure for storing the Point Pair Feature (CPPF) values
            * \ingroup common

        """
        f1: float
        f2: float
        f3: float
        f4: float
        f5: float
        f6: float
        f7: float
        f8: float
        f9: float
        f10: float
        alpha_m: float

        @overload
        def __init__(self, _alpha: float = 0.) -> None:
            pass

        @overload
        def __init__(
            self,
            _f1: float,
            _f2: float,
            _f3: float,
            _f4: float,
            _f5: float,
            _f6: float,
            _f7: float,
            _f8: float,
            _f9: float,
            _f10: float,
            _alpha: float = 0.
            ) -> None:
            pass


    class PPFRGBSignature:
        """* \brief A point structure for storing the Point Pair Color Feature (PPFRGB) values
            * \ingroup common

        """
        f1: float = 0.
        f2: float = 0.
        f3: float = 0.
        f4: float = 0.
        r_ratio: float = 0.
        g_ratio: float = 0.
        b_ratio: float = 0.
        alpha_m: float = 0.

        @overload
        def __init__(self, _alpha: float = 0.) -> None:
            pass

        @overload
        def __init__(
            self,
            _f1: float,
            _f2: float,
            _f3: float,
            _f4: float,
            _alpha: float = 0.
            ) -> None:
            pass

        @overload
        def __init__(
            self,
            _f1: float,
            _f2: float,
            _f3: float,
            _f4: float,
            _alpha: float,
            _r: float,
            _g: float,
            _b: float
            ) -> None:
            pass


    class NormalBasedSignature12:
        """* \brief A point structure representing the Normal Based Signature for
            * a feature matrix of 4-by-3
            * \ingroup common

        """
        values: np.ndarray  # ndarray[type=float, size=12] default:float(0.)

        def __init__(self) -> None:
            pass


    class ShapeContext1980:
        """* \brief A point structure representing a Shape Context.
            * \ingroup common

        """
        descriptor: np.ndarray  # ndarray[type=float, size=1980] default:float(0.)
        rf: np.ndarray          # ndarray[type=float, size=9] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass


    class UniqueShapeContext1960:
        """* \brief A point structure representing a Unique Shape Context.
            * \ingroup common

        """
        descriptor: np.ndarray  # ndarray[type=float, size=1960] default:float(0.)
        rf: np.ndarray          # ndarray[type=float, size=9] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass


    class SHOT352:
        """* \brief A point structure representing the generic Signature of Histograms of OrienTations (SHOT) - shape only.
            * \ingroup common

        """
        descriptor: np.ndarray  # ndarray[type=float, size=352] default:float(0.)
        rf: np.ndarray          # ndarray[type=float, size=9] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass



    class SHOT1344:
        """* \brief A point structure representing the generic Signature of Histograms of OrienTations (SHOT) - shape+color.
            * \ingroup common

        """
        descriptor: np.ndarray  # ndarray[type=float, size=1344] default:float(0.)
        rf: np.ndarray          # ndarray[type=float, size=9] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass



    class _ReferenceFrame:
        """* \brief A structure representing the Local Reference Frame of a point.
            *  \ingroup common

        """

        @overload
        def get_x_axis_vector3f_map(self) -> Eigen.Map[Eigen.Vector3f]:
            pass
        @overload
        def get_x_axis_vector3f_map(self) -> Eigen.Map[ Eigen.Vector3f]:
            pass
        @overload
        def get_y_axis_vector3f_map(self) -> Eigen.Map[Eigen.Vector3f]:
            pass
        @overload
        def get_y_axis_vector3f_map(self) -> Eigen.Map[ Eigen.Vector3f]:
            pass
        @overload
        def get_z_axis_vector3f_map(self) -> Eigen.Map[Eigen.Vector3f]:
            pass
        @overload
        def get_z_axis_vector3f_map(self) -> Eigen.Map[ Eigen.Vector3f]:
            pass
        @overload
        def get_matrix3f_map(self) -> Eigen.Map[Eigen.Matrix3f]:
            pass
        @overload
        def get_matrix3f_map(self) -> Eigen.Map[ Eigen.Matrix3f]:
            pass

        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class ReferenceFrame(pcl._ReferenceFrame):
        @overload
        def __init__(self, p: _ReferenceFrame) -> None:
            pass

        @overload
        def __init__(self) -> None:
            pass




    class FPFHSignature33:
        """* \brief A point structure representing the Fast Point Feature Histogram (FPFH).
            * \ingroup common

        """
        histogram: np.ndarray  # ndarray[type=float, size=33] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass


    class VFHSignature308:
        """* \brief A point structure representing the Viewpoint Feature Histogram (VFH).
            * \ingroup common

        """
        histogram: np.ndarray  # ndarray[type=float, size=308] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass


    class GRSDSignature21:
        """* \brief A point structure representing the Global Radius-based Surface Descriptor (GRSD).
            * \ingroup common

        """
        histogram: np.ndarray  # ndarray[type=float, size=21] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass


    class BRISKSignature512:
        """* \brief A point structure representing the Binary Robust Invariant Scalable Keypoints (BRISK).
            * \ingroup common

        """
        scale: float = 0.
        orientation: float = 0.
        @staticmethod
        def descriptor_size() -> int:
            pass

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _scale: float, _orientation: float) -> None:
            pass


    class ESFSignature640:
        """* \brief A point structure representing the Ensemble of Shape Functions (ESF).
            * \ingroup common

        """
        histogram: np.ndarray  # ndarray[type=float, size=640] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass


    class GASDSignature512:
        """* \brief A point structure representing the Globally Aligned Spatial Distribution (GASD) shape descriptor.
          * \ingroup common

        """
        histogram: np.ndarray  # ndarray[type=float, size=512] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass


    class GASDSignature984:
        """* \brief A point structure representing the Globally Aligned Spatial Distribution (GASD) shape and color descriptor.
          * \ingroup common

        """
        histogram: np.ndarray  # ndarray[type=float, size=984] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass


    class GASDSignature7992:
        """* \brief A point structure representing the Globally Aligned Spatial Distribution (GASD) shape and color descriptor.
          * \ingroup common

        """
        histogram: np.ndarray  # ndarray[type=float, size=7992] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass


    class GFPFHSignature16:
        """* \brief A point structure representing the GFPFH descriptor with 16 bins.
            * \ingroup common

        """
        histogram: np.ndarray  # ndarray[type=float, size=16] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        def __init__(self) -> None:
            pass


    class Narf36:
        """* \brief A point structure representing the Narf descriptor.
            * \ingroup common

        """
        x: float = 0.
        y: float = 0.
        z: float = 0.
        roll: float = 0.
        pitch: float = 0.
        yaw: float = 0.
        descriptor: np.ndarray  # ndarray[type=float, size=36] default:float(0.)
        @staticmethod
        def descriptor_size() -> int:
            pass

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _roll: float,
            _pitch: float,
            _yaw: float
            ) -> None:
            pass


    class BorderDescription:
        """* \brief A structure to store if a point in a range image lies on a border between an obstacle and the background.
            * \ingroup common

        """
        x: int = 0
        y: int = 0
        traits: BorderTraits
        #std::vector<const BorderDescription*> neighbors;

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _x: int, _y: int) -> None:
            pass



    class IntensityGradient:
        """* \brief A point structure representing the intensity gradient of an XYZI point cloud.
            * \ingroup common

        """

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float) -> None:
            pass


    class _PointWithScale:


        #* \brief Computed orientation of the keypoint (-1 if not applicable).
        angle: float
        #* \brief The response by which the most strong keypoints have been selected.
        response: float
        #* \brief octave (pyramid layer) from which the keypoint has been extracted.
        octave: int

        def __init__(
            self,
            angle: float = float(),
            response: float = float(),
            octave: int = int()
            ) -> None:
            """Auto-generated default constructor with named params"""
            pass

    class PointWithScale(pcl._PointWithScale):
        """* \brief A point structure representing a 3-D position and scale.
            * \ingroup common

        """
        @overload
        def __init__(self, p: _PointWithScale) -> None:
            pass

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _scale: float = 1.,
            _angle: float = -1.,
            _response: float = 0.,
            _octave: int = 0
            ) -> None:
            pass



    class _PointSurfel:
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    class PointSurfel(pcl._PointSurfel):
        """* \brief A surfel, that is, a point structure representing Euclidean xyz coordinates, together with normal coordinates, a RGBA color, a radius, a confidence value and the surface curvature estimate.
            * \ingroup common

        """
        @overload
        def __init__(self, p: _PointSurfel) -> None:
            pass

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _nx: float,
            _ny: float,
            _nz: float,
            _r: std.int,
            _g: std.int,
            _b: std.int,
            _a: std.int,
            _radius: float,
            _confidence: float,
            _curvature: float
            ) -> None:
            pass



    class _PointDEM:
        intensity: PCL_ADD_POINT4D float
        intensity_variance: float
        height_variance: float
        def __init__(
            self,
            intensity_variance: float = float(),
            height_variance: float = float()
            ) -> None:
            """Auto-generated default constructor with named params"""
            pass

    class PointDEM(pcl._PointDEM):
        """* \brief A point structure representing Digital Elevation Map.
            * \ingroup common

        """
        @overload
        def __init__(self, p: _PointDEM) -> None:
            pass

        @overload
        def __init__(self) -> None:
            pass

        @overload
        def __init__(self, _x: float, _y: float, _z: float) -> None:
            pass

        @overload
        def __init__(
            self,
            _x: float,
            _y: float,
            _z: float,
            _intensity: float,
            _intensity_variance: float,
            _height_variance: float
            ) -> None:
            pass



    # Allow float 'rgb' data to match to the newer uint32 'rgba' tag. This is so
    # you can load old 'rgb' PCD files into e.g. a PointCloud<PointXYZRGBA>.


    # We're doing a lot of black magic with Boost here, so disable warnings in Maintainer mode, as we will never
    # be able to fix them anyway




    # <submodule traits>
    class traits:  # Proxy class that introduces typings for the *submodule* traits
        pass  # (This corresponds to a C++ namespace. All method are static!)




        #* \brief Traits defined for ease of use with fields already registered before
        #   *
        #   * has_<fields to be detected>: struct with `value` datamember defined at compiletime
        #   * has_<fields to be detected>_v: constexpr boolean
        #   * Has<Fields to be detected>: concept modelling name alias for `enable_if`
        #





























    # </submodule traits>

# </submodule pcl>
####################    </generated_from:point_types.hpp>    ####################


####################    <generated_from:PointIndices.h>    ####################


# Include the correct Header path here


# <submodule pcl>
class pcl:  # Proxy class that introduces typings for the *submodule* pcl
    pass  # (This corresponds to a C++ namespace. All method are static!)
    """ namespace pcl"""
    class PointIndices:
        """ struct PointIndices"""

        def __init__(self) -> None:
            pass

        header: .pcl.PCLHeader

        indices: Indices



# </submodule pcl>
####################    </generated_from:PointIndices.h>    ####################


####################    <generated_from:point_cloud.h>    ####################
#
# * Software License Agreement (BSD License)
# *
# *  Point Cloud Library (PCL) - www.pointclouds.org
# *  Copyright (c) 2010-2012, Willow Garage, Inc.
# *  Copyright (c) 2012-, Open Perception, Inc.
# *
# *  All rights reserved.
# *
# *  Redistribution and use in source and binary forms, with or without
# *  modification, are permitted provided that the following conditions
# *  are met:
# *
# *   * Redistributions of source code must retain the above copyright
# *     notice, this list of conditions and the following disclaimer.
# *   * Redistributions in binary form must reproduce the above
# *     copyright notice, this list of conditions and the following
# *     disclaimer in the documentation and/or other materials provided
# *     with the distribution.
# *   * Neither the name of the copyright holder(s) nor the names of its
# *     contributors may be used to endorse or promote products derived
# *     from this software without specific prior written permission.
# *
# *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# *  POSSIBILITY OF SUCH DAMAGE.
# *
#






# <submodule pcl>
class pcl:  # Proxy class that introduces typings for the *submodule* pcl
    pass  # (This corresponds to a C++ namespace. All method are static!)




    #  ------------------------------------------------------------------------
    #      <template specializations for class PointCloud>
    class PointCloud_pcl_PointXYZ:  # Python specialization for PointCloud<pcl::PointXYZ>
        """* \brief PointCloud represents the base class in PCL for storing collections of 3D points.
            *
            * The class is templated, which means you need to specify the type of data
            * that it should contain. For example, to create a point cloud that holds 4
            * random XYZ data points, use:
            *
            * \code
            * pcl::PointCloud<pcl::PointXYZ> cloud;
            * cloud.push_back (pcl::PointXYZ (rand (), rand (), rand ()));
            * cloud.push_back (pcl::PointXYZ (rand (), rand (), rand ()));
            * cloud.push_back (pcl::PointXYZ (rand (), rand (), rand ()));
            * cloud.push_back (pcl::PointXYZ (rand (), rand (), rand ()));
            * \endcode
            *
            * The PointCloud class contains the following elements:
            *   - \b width - specifies the width of the point cloud dataset in the number of points. WIDTH has two meanings:
            *     - it can specify the total number of points in the cloud (equal with POINTS see below) for unorganized datasets;
            *     - it can specify the width (total number of points in a row) of an organized point cloud dataset.
            *   \a Mandatory.
            *   - \b height - specifies the height of the point cloud dataset in the number of points. HEIGHT has two meanings:
            *     - it can specify the height (total number of rows) of an organized point cloud dataset;
            *     - it is set to 1 for unorganized datasets (thus used to check whether a dataset is organized or not).
            *   \a Mandatory.
            *   - \b points - the data array where all points of type <b>PointT</b> are stored. \a Mandatory.
            *
            *   - \b is_dense - specifies if all the data in <b>points</b> is finite (True), or whether it might contain Inf/NaN values
            * (False). \a Mandatory.
            *
            *   - \b sensor_origin_ - specifies the sensor acquisition pose (origin/translation). \a Optional.
            *   - \b sensor_orientation_ - specifies the sensor acquisition pose (rotation). \a Optional.
            *
            * \author Patrick Mihelich, Radu B. Rusu

        """
        @overload
        def __init__(self) -> None:
            """* \brief Default constructor. Sets \ref is_dense to True, \ref width
                    * and \ref height to 0, and the \ref sensor_origin_ and \ref
                    * sensor_orientation_ to identity.

            """
            pass

        @overload
        def __init__(self, pc: PointCloud[PointXYZ], indices: Indices) -> None:
            """* \brief Copy constructor from point cloud subset
                    * \param[in] pc the cloud to copy into this
                    * \param[in] indices the subset to copy

            """
            pass

        @overload
        def __init__(
            self,
            width_: std.int,
            height_: std.int,
            value_: PointXYZ = PointT ()
            ) -> None:
            """* \brief Allocate constructor from point cloud subset
                    * \param[in] width_ the cloud width
                    * \param[in] height_ the cloud height
                    * \param[in] value_ default value

            """
            pass

        #TODO: check if copy/move constructors/assignment operators are needed

        def __iadd__(self, rhs: PointCloud) -> PointCloud:
            """* \brief Add a point cloud to the current cloud.
                    * \param[in] rhs the cloud to add to the current cloud
                    * \return the new cloud as a concatenation of the current cloud and the new given cloud

            """
            pass

        def __add__(self, rhs: PointCloud) -> PointCloud:
            """* \brief Add a point cloud to another cloud.
                    * \param[in] rhs the cloud to add to the current cloud
                    * \return the new cloud as a concatenation of the current cloud and the new given cloud

            """
            pass

        @staticmethod
        @overload
        def concatenate(cloud1: PointCloud[PointXYZ], cloud2: PointCloud[PointXYZ]) -> bool:
            pass

        @staticmethod
        @overload
        def concatenate(
            cloud1: PointCloud[PointXYZ],
            cloud2: PointCloud[PointXYZ],
            cloud_out: PointCloud[PointXYZ]
            ) -> bool:
            pass

        @overload
        def at(self, column: int, row: int) -> PointXYZ:
            """* \brief Obtain the point given by the (column, row) coordinates. Only works on organized
                    * datasets (those that have height != 1).
                    * \param[in] column the column coordinate
                    * \param[in] row the row coordinate

            """
            pass

        @overload
        def at(self, column: int, row: int) -> PointXYZ:
            """* \brief Obtain the point given by the (column, row) coordinates. Only works on organized
                    * datasets (those that have height != 1).
                    * \param[in] column the column coordinate
                    * \param[in] row the row coordinate

            """
            pass

        @overload
        def __call__(self, column: std.int, row: std.int) -> PointXYZ:
            """* \brief Obtain the point given by the (column, row) coordinates. Only works on organized
                    * datasets (those that have height != 1).
                    * \param[in] column the column coordinate
                    * \param[in] row the row coordinate

            """
            pass

        @overload
        def __call__(self, column: std.int, row: std.int) -> PointXYZ:
            """* \brief Obtain the point given by the (column, row) coordinates. Only works on organized
                    * datasets (those that have height != 1).
                    * \param[in] column the column coordinate
                    * \param[in] row the row coordinate

            """
            pass

        def is_organized(self) -> bool:
            """* \brief Return whether a dataset is organized (e.g., arranged in a structured grid).
                    * \note The height value must be different than 1 for a dataset to be organized.

            """
            pass

        @overload
        def get_matrix_xf_map(
            self,
            dim: int,
            stride: int,
            offset: int
            ) -> Eigen.Map[Eigen.MatrixXf, Eigen.Aligned, Eigen.OuterStride[]]:
            """* \brief Return an Eigen MatrixXf (assumes float values) mapped to the specified dimensions of the PointCloud.
                    * \note This method is for advanced users only! Use with care!
                    *
                    * \attention Compile time flags used for Eigen might affect the dimension of the Eigen::Map returned. If Eigen
                    *   is using row major storage, the matrix shape would be (number of Points X elements in a Point) else
                    *   the matrix shape would be (elements in a Point X number of Points). Essentially,
                    *   * Major direction: number of points in cloud
                    *   * Minor direction: number of point dimensions
                    * By default, as of Eigen 3.3, Eigen uses Column major storage
                    *
                    * \param[in] dim the number of dimensions to consider for each point
                    * \param[in] stride the number of values in each point (will be the number of values that separate two of the columns)
                    * \param[in] offset the number of dimensions to skip from the beginning of each point
                    *            (stride = offset + dim + x, where x is the number of dimensions to skip from the end of each point)
                    * \note for getting only XYZ coordinates out of PointXYZ use dim=3, stride=4 and offset=0 due to the alignment.
                    * \attention PointT types are most of the time aligned, so the offsets are not continuous!

            """
            pass

        @overload
        def get_matrix_xf_map(
            self,
            dim: int,
            stride: int,
            offset: int
            ) -> Eigen.Map[Eigen.MatrixXf, Eigen.Aligned, Eigen.OuterStride[]]:
            """* \brief Return an Eigen MatrixXf (assumes float values) mapped to the specified dimensions of the PointCloud.
                    * \note This method is for advanced users only! Use with care!
                    *
                    * \attention Compile time flags used for Eigen might affect the dimension of the Eigen::Map returned. If Eigen
                    *   is using row major storage, the matrix shape would be (number of Points X elements in a Point) else
                    *   the matrix shape would be (elements in a Point X number of Points). Essentially,
                    *   * Major direction: number of points in cloud
                    *   * Minor direction: number of point dimensions
                    * By default, as of Eigen 3.3, Eigen uses Column major storage
                    *
                    * \param[in] dim the number of dimensions to consider for each point
                    * \param[in] stride the number of values in each point (will be the number of values that separate two of the columns)
                    * \param[in] offset the number of dimensions to skip from the beginning of each point
                    *            (stride = offset + dim + x, where x is the number of dimensions to skip from the end of each point)
                    * \note for getting only XYZ coordinates out of PointXYZ use dim=3, stride=4 and offset=0 due to the alignment.
                    * \attention PointT types are most of the time aligned, so the offsets are not continuous!

            """
            pass

        @overload
        def get_matrix_xf_map(
            self
            ) -> Eigen.Map[Eigen.MatrixXf, Eigen.Aligned, Eigen.OuterStride[]]:
            """*
                   * \brief Return an Eigen MatrixXf (assumes float values) mapped to the PointCloud.
                   * \note This method is for advanced users only! Use with care!
                   * \attention PointT types are most of the time aligned, so the offsets are not continuous!
                   * \overload Eigen::Map<Eigen::MatrixXf, Eigen::Aligned, Eigen::OuterStride<> > pcl::PointCloud::getMatrixXfMap ()

            """
            pass

        @overload
        def get_matrix_xf_map(
            self
            ) -> Eigen.Map[Eigen.MatrixXf, Eigen.Aligned, Eigen.OuterStride[]]:
            """*
                   * \brief Return an Eigen MatrixXf (assumes float values) mapped to the PointCloud.
                   * \note This method is for advanced users only! Use with care!
                   * \attention PointT types are most of the time aligned, so the offsets are not continuous!
                   * \overload const Eigen::Map<Eigen::MatrixXf, Eigen::Aligned, Eigen::OuterStride<> > pcl::PointCloud::getMatrixXfMap () const

            """
            pass

        #* \brief The point cloud header. It contains information about the acquisition time.
        header: pcl.PCLHeader

        #* \brief The point data.
        points: List[pcl.PointXYZ, Eigen.aligned_allocator[pcl.PointXYZ]]

        #* \brief The point cloud width (if organized as an image-structure).
        width: std.int = 0
        #* \brief The point cloud height (if organized as an image-structure).
        height: std.int = 0

        #* \brief True if no points are invalid (e.g., have NaN or Inf values in any of their floating point fields).
        is_dense: bool = True

        #* \brief Sensor acquisition pose (origin/translation).
        sensor_origin_: Eigen.Vector4f = Eigen.Vector4f.Zero ()
        #* \brief Sensor acquisition pose (rotation).
        sensor_orientation_: Eigen.Quaternionf = Eigen.Quaternionf.Identity ()


        # std container compatibility typedefs according to
        # http://en.cppreference.com/w/cpp/concept/Container

        # iterators
        @overload
        def begin(self) -> iterator:
            pass
        @overload
        def end(self) -> iterator:
            pass
        @overload
        def begin(self) -> const_iterator:
            pass
        @overload
        def end(self) -> const_iterator:
            pass
        def cbegin(self) -> const_iterator:
            pass
        def cend(self) -> const_iterator:
            pass
        @overload
        def rbegin(self) -> reverse_iterator:
            pass
        @overload
        def rend(self) -> reverse_iterator:
            pass
        @overload
        def rbegin(self) -> const_reverse_iterator:
            pass
        @overload
        def rend(self) -> const_reverse_iterator:
            pass
        def crbegin(self) -> const_reverse_iterator:
            pass
        def crend(self) -> const_reverse_iterator:
            pass

        #capacity
        def size(self) -> std.int:
            pass
        def max_size(self) -> index_t:
            pass
        def reserve(self, n: std.int) -> None:
            pass
        def empty(self) -> bool:
            pass
        @overload
        def data(self) -> PointXYZ:
            pass
        @overload
        def data(self) -> PointXYZ:
            pass

        @overload
        def resize(self, count: std.int) -> None:
            """*
                   * \brief Resizes the container to contain `count` elements
                   * \details
                   * * If the current size is greater than `count`, the pointcloud is reduced to its
                   * first `count` elements
                   * * If the current size is less than `count`, additional default-inserted points
                   * are appended
                   * \note This potentially breaks the organized structure of the cloud by setting
                   * the height to 1 IFF `width * height != count`!
                   * \param[in] count new size of the point cloud

            """
            pass

        @overload
        def resize(self, new_width: uindex_t, new_height: uindex_t) -> None:
            """*
                   * \brief Resizes the container to contain `new_width * new_height` elements
                   * \details
                   * * If the current size is greater than the requested size, the pointcloud
                   * is reduced to its first requested elements
                   * * If the current size is less then the requested size, additional
                   * default-inserted points are appended
                   * \param[in] new_width new width of the point cloud
                   * \param[in] new_height new height of the point cloud

            """
            pass

        @overload
        def resize(self, count: index_t, value: PointXYZ) -> None:
            """*
                   * \brief Resizes the container to contain count elements
                   * \details
                   * * If the current size is greater than `count`, the pointcloud is reduced to its
                   * first `count` elements
                   * * If the current size is less than `count`, additional copies of `value` are
                   * appended
                   * \note This potentially breaks the organized structure of the cloud by setting
                   * the height to 1 IFF `width * height != count`!
                   * \param[in] count new size of the point cloud
                   * \param[in] value the value to initialize the new points with

            """
            pass

        @overload
        def resize(self, new_width: index_t, new_height: index_t, value: PointXYZ) -> None:
            """*
                   * \brief Resizes the container to contain count elements
                   * \details
                   * * If the current size is greater then the requested size, the pointcloud
                   * is reduced to its first requested elements
                   * * If the current size is less then the requested size, additional
                   * default-inserted points are appended
                   * \param[in] new_width new width of the point cloud
                   * \param[in] new_height new height of the point cloud
                   * \param[in] value the value to initialize the new points with

            """
            pass

        #element access
        @overload
        def __getitem__(self, n: std.int) -> PointXYZ:
            pass
        @overload
        def __getitem__(self, n: std.int) -> PointXYZ:
            pass
        @overload
        def at(self, n: std.int) -> PointXYZ:
            pass
        @overload
        def at(self, n: std.int) -> PointXYZ:
            pass
        @overload
        def front(self) -> PointXYZ:
            pass
        @overload
        def front(self) -> PointXYZ:
            pass
        @overload
        def back(self) -> PointXYZ:
            pass
        @overload
        def back(self) -> PointXYZ:
            pass

        @overload
        def assign(self, count: index_t, value: PointXYZ) -> None:
            """*
                   * \brief Replaces the points with `count` copies of `value`
                   * \note This breaks the organized structure of the cloud by setting the height to
                   * 1!
                   * \param[in] count new size of the point cloud
                   * \param[in] value value each point of the cloud should have

            """
            pass

        @overload
        def assign(self, new_width: index_t, new_height: index_t, value: PointXYZ) -> None:
            """*
                   * \brief Replaces the points with `new_width * new_height` copies of `value`
                   * \param[in] new_width new width of the point cloud
                   * \param[in] new_height new height of the point cloud
                   * \param[in] value value each point of the cloud should have

            """
            pass



        @overload
        def assign(self, ilist: std.initializer_list[PointXYZ]) -> None:
            """*
                   * \brief Replaces the points with the elements from the initializer list `ilist`
                   * \note This breaks the organized structure of the cloud by setting the height to
                   * 1!

            """
            pass

        @overload
        def assign(self, ilist: std.initializer_list[PointXYZ], new_width: index_t) -> None:
            """*
                   * \brief Replaces the points with the elements from the initializer list `ilist`
                   * \note This calculates the height based on size and width provided. This means
                   * the assignment happens even if the size is not perfectly divisible by width
                   * \param[in] ilist initializer list from which the points are copied
                   * \param[in] new_width new width of the point cloud

            """
            pass

        def push_back(self, pt: PointXYZ) -> None:
            """* \brief Insert a new point in the cloud, at the end of the container.
                    * \note This breaks the organized structure of the cloud by setting the height to 1!
                    * \param[in] pt the point to insert

            """
            pass

        def transient_push_back(self, pt: PointXYZ) -> None:
            """* \brief Insert a new point in the cloud, at the end of the container.
                    * \note This assumes the user would correct the width and height later on!
                    * \param[in] pt the point to insert

            """
            pass



        @overload
        def insert(self, position: iterator, pt: PointXYZ) -> iterator:
            """* \brief Insert a new point in the cloud, given an iterator.
                    * \note This breaks the organized structure of the cloud by setting the height to 1!
                    * \param[in] position where to insert the point
                    * \param[in] pt the point to insert
                    * \return returns the new position iterator

            """
            pass

        @overload
        def transient_insert(self, position: iterator, pt: PointXYZ) -> iterator:
            """* \brief Insert a new point in the cloud, given an iterator.
                    * \note This assumes the user would correct the width and height later on!
                    * \param[in] position where to insert the point
                    * \param[in] pt the point to insert
                    * \return returns the new position iterator

            """
            pass

        @overload
        def insert(self, position: iterator, n: std.int, pt: PointXYZ) -> None:
            """* \brief Insert a new point in the cloud N times, given an iterator.
                    * \note This breaks the organized structure of the cloud by setting the height to 1!
                    * \param[in] position where to insert the point
                    * \param[in] n the number of times to insert the point
                    * \param[in] pt the point to insert

            """
            pass

        @overload
        def transient_insert(self, position: iterator, n: std.int, pt: PointXYZ) -> None:
            """* \brief Insert a new point in the cloud N times, given an iterator.
                    * \note This assumes the user would correct the width and height later on!
                    * \param[in] position where to insert the point
                    * \param[in] n the number of times to insert the point
                    * \param[in] pt the point to insert

            """
            pass





        @overload
        def erase(self, position: iterator) -> iterator:
            """* \brief Erase a point in the cloud.
                    * \note This breaks the organized structure of the cloud by setting the height to 1!
                    * \param[in] position what data point to erase
                    * \return returns the new position iterator

            """
            pass

        @overload
        def transient_erase(self, position: iterator) -> iterator:
            """* \brief Erase a point in the cloud.
                    * \note This assumes the user would correct the width and height later on!
                    * \param[in] position what data point to erase
                    * \return returns the new position iterator

            """
            pass

        @overload
        def erase(self, first: iterator, last: iterator) -> iterator:
            """* \brief Erase a set of points given by a (first, last) iterator pair
                    * \note This breaks the organized structure of the cloud by setting the height to 1!
                    * \param[in] first where to start erasing points from
                    * \param[in] last where to stop erasing points from
                    * \return returns the new position iterator

            """
            pass

        @overload
        def transient_erase(self, first: iterator, last: iterator) -> iterator:
            """* \brief Erase a set of points given by a (first, last) iterator pair
                    * \note This assumes the user would correct the width and height later on!
                    * \param[in] first where to start erasing points from
                    * \param[in] last where to stop erasing points from
                    * \return returns the new position iterator

            """
            pass

        def swap(self, rhs: PointCloud[PointXYZ]) -> None:
            """* \brief Swap a point cloud with another cloud.
                    * \param[in,out] rhs point cloud to swap this with

            """
            pass

        def clear(self) -> None:
            """* \brief Removes all points in a cloud and sets the width and height to 0."""
            pass

        def make_shared(self) -> Ptr:
            """* \brief Copy the cloud to the heap and return a smart pointer
                    * Note that deep copy is performed, so avoid using this function on non-empty clouds.
                    * The changes of the returned cloud are not mirrored back to this one.
                    * \return shared pointer to the copy of the cloud

            """
            pass



    class PointCloud_pcl_PointXYZRGBA:  # Python specialization for PointCloud<pcl::PointXYZRGBA>
        """* \brief PointCloud represents the base class in PCL for storing collections of 3D points.
            *
            * The class is templated, which means you need to specify the type of data
            * that it should contain. For example, to create a point cloud that holds 4
            * random XYZ data points, use:
            *
            * \code
            * pcl::PointCloud<pcl::PointXYZ> cloud;
            * cloud.push_back (pcl::PointXYZ (rand (), rand (), rand ()));
            * cloud.push_back (pcl::PointXYZ (rand (), rand (), rand ()));
            * cloud.push_back (pcl::PointXYZ (rand (), rand (), rand ()));
            * cloud.push_back (pcl::PointXYZ (rand (), rand (), rand ()));
            * \endcode
            *
            * The PointCloud class contains the following elements:
            *   - \b width - specifies the width of the point cloud dataset in the number of points. WIDTH has two meanings:
            *     - it can specify the total number of points in the cloud (equal with POINTS see below) for unorganized datasets;
            *     - it can specify the width (total number of points in a row) of an organized point cloud dataset.
            *   \a Mandatory.
            *   - \b height - specifies the height of the point cloud dataset in the number of points. HEIGHT has two meanings:
            *     - it can specify the height (total number of rows) of an organized point cloud dataset;
            *     - it is set to 1 for unorganized datasets (thus used to check whether a dataset is organized or not).
            *   \a Mandatory.
            *   - \b points - the data array where all points of type <b>PointT</b> are stored. \a Mandatory.
            *
            *   - \b is_dense - specifies if all the data in <b>points</b> is finite (True), or whether it might contain Inf/NaN values
            * (False). \a Mandatory.
            *
            *   - \b sensor_origin_ - specifies the sensor acquisition pose (origin/translation). \a Optional.
            *   - \b sensor_orientation_ - specifies the sensor acquisition pose (rotation). \a Optional.
            *
            * \author Patrick Mihelich, Radu B. Rusu

        """
        @overload
        def __init__(self) -> None:
            """* \brief Default constructor. Sets \ref is_dense to True, \ref width
                    * and \ref height to 0, and the \ref sensor_origin_ and \ref
                    * sensor_orientation_ to identity.

            """
            pass

        @overload
        def __init__(self, pc: PointCloud[PointXYZRGBA], indices: Indices) -> None:
            """* \brief Copy constructor from point cloud subset
                    * \param[in] pc the cloud to copy into this
                    * \param[in] indices the subset to copy

            """
            pass

        @overload
        def __init__(
            self,
            width_: std.int,
            height_: std.int,
            value_: PointXYZRGBA = PointT ()
            ) -> None:
            """* \brief Allocate constructor from point cloud subset
                    * \param[in] width_ the cloud width
                    * \param[in] height_ the cloud height
                    * \param[in] value_ default value

            """
            pass

        #TODO: check if copy/move constructors/assignment operators are needed

        def __iadd__(self, rhs: PointCloud) -> PointCloud:
            """* \brief Add a point cloud to the current cloud.
                    * \param[in] rhs the cloud to add to the current cloud
                    * \return the new cloud as a concatenation of the current cloud and the new given cloud

            """
            pass

        def __add__(self, rhs: PointCloud) -> PointCloud:
            """* \brief Add a point cloud to another cloud.
                    * \param[in] rhs the cloud to add to the current cloud
                    * \return the new cloud as a concatenation of the current cloud and the new given cloud

            """
            pass

        @staticmethod
        @overload
        def concatenate(
            cloud1: PointCloud[PointXYZRGBA],
            cloud2: PointCloud[PointXYZRGBA]
            ) -> bool:
            pass

        @staticmethod
        @overload
        def concatenate(
            cloud1: PointCloud[PointXYZRGBA],
            cloud2: PointCloud[PointXYZRGBA],
            cloud_out: PointCloud[PointXYZRGBA]
            ) -> bool:
            pass

        @overload
        def at(self, column: int, row: int) -> PointXYZRGBA:
            """* \brief Obtain the point given by the (column, row) coordinates. Only works on organized
                    * datasets (those that have height != 1).
                    * \param[in] column the column coordinate
                    * \param[in] row the row coordinate

            """
            pass

        @overload
        def at(self, column: int, row: int) -> PointXYZRGBA:
            """* \brief Obtain the point given by the (column, row) coordinates. Only works on organized
                    * datasets (those that have height != 1).
                    * \param[in] column the column coordinate
                    * \param[in] row the row coordinate

            """
            pass

        @overload
        def __call__(self, column: std.int, row: std.int) -> PointXYZRGBA:
            """* \brief Obtain the point given by the (column, row) coordinates. Only works on organized
                    * datasets (those that have height != 1).
                    * \param[in] column the column coordinate
                    * \param[in] row the row coordinate

            """
            pass

        @overload
        def __call__(self, column: std.int, row: std.int) -> PointXYZRGBA:
            """* \brief Obtain the point given by the (column, row) coordinates. Only works on organized
                    * datasets (those that have height != 1).
                    * \param[in] column the column coordinate
                    * \param[in] row the row coordinate

            """
            pass

        def is_organized(self) -> bool:
            """* \brief Return whether a dataset is organized (e.g., arranged in a structured grid).
                    * \note The height value must be different than 1 for a dataset to be organized.

            """
            pass

        @overload
        def get_matrix_xf_map(
            self,
            dim: int,
            stride: int,
            offset: int
            ) -> Eigen.Map[Eigen.MatrixXf, Eigen.Aligned, Eigen.OuterStride[]]:
            """* \brief Return an Eigen MatrixXf (assumes float values) mapped to the specified dimensions of the PointCloud.
                    * \note This method is for advanced users only! Use with care!
                    *
                    * \attention Compile time flags used for Eigen might affect the dimension of the Eigen::Map returned. If Eigen
                    *   is using row major storage, the matrix shape would be (number of Points X elements in a Point) else
                    *   the matrix shape would be (elements in a Point X number of Points). Essentially,
                    *   * Major direction: number of points in cloud
                    *   * Minor direction: number of point dimensions
                    * By default, as of Eigen 3.3, Eigen uses Column major storage
                    *
                    * \param[in] dim the number of dimensions to consider for each point
                    * \param[in] stride the number of values in each point (will be the number of values that separate two of the columns)
                    * \param[in] offset the number of dimensions to skip from the beginning of each point
                    *            (stride = offset + dim + x, where x is the number of dimensions to skip from the end of each point)
                    * \note for getting only XYZ coordinates out of PointXYZ use dim=3, stride=4 and offset=0 due to the alignment.
                    * \attention PointT types are most of the time aligned, so the offsets are not continuous!

            """
            pass

        @overload
        def get_matrix_xf_map(
            self,
            dim: int,
            stride: int,
            offset: int
            ) -> Eigen.Map[Eigen.MatrixXf, Eigen.Aligned, Eigen.OuterStride[]]:
            """* \brief Return an Eigen MatrixXf (assumes float values) mapped to the specified dimensions of the PointCloud.
                    * \note This method is for advanced users only! Use with care!
                    *
                    * \attention Compile time flags used for Eigen might affect the dimension of the Eigen::Map returned. If Eigen
                    *   is using row major storage, the matrix shape would be (number of Points X elements in a Point) else
                    *   the matrix shape would be (elements in a Point X number of Points). Essentially,
                    *   * Major direction: number of points in cloud
                    *   * Minor direction: number of point dimensions
                    * By default, as of Eigen 3.3, Eigen uses Column major storage
                    *
                    * \param[in] dim the number of dimensions to consider for each point
                    * \param[in] stride the number of values in each point (will be the number of values that separate two of the columns)
                    * \param[in] offset the number of dimensions to skip from the beginning of each point
                    *            (stride = offset + dim + x, where x is the number of dimensions to skip from the end of each point)
                    * \note for getting only XYZ coordinates out of PointXYZ use dim=3, stride=4 and offset=0 due to the alignment.
                    * \attention PointT types are most of the time aligned, so the offsets are not continuous!

            """
            pass

        @overload
        def get_matrix_xf_map(
            self
            ) -> Eigen.Map[Eigen.MatrixXf, Eigen.Aligned, Eigen.OuterStride[]]:
            """*
                   * \brief Return an Eigen MatrixXf (assumes float values) mapped to the PointCloud.
                   * \note This method is for advanced users only! Use with care!
                   * \attention PointT types are most of the time aligned, so the offsets are not continuous!
                   * \overload Eigen::Map<Eigen::MatrixXf, Eigen::Aligned, Eigen::OuterStride<> > pcl::PointCloud::getMatrixXfMap ()

            """
            pass

        @overload
        def get_matrix_xf_map(
            self
            ) -> Eigen.Map[Eigen.MatrixXf, Eigen.Aligned, Eigen.OuterStride[]]:
            """*
                   * \brief Return an Eigen MatrixXf (assumes float values) mapped to the PointCloud.
                   * \note This method is for advanced users only! Use with care!
                   * \attention PointT types are most of the time aligned, so the offsets are not continuous!
                   * \overload const Eigen::Map<Eigen::MatrixXf, Eigen::Aligned, Eigen::OuterStride<> > pcl::PointCloud::getMatrixXfMap () const

            """
            pass

        #* \brief The point cloud header. It contains information about the acquisition time.
        header: pcl.PCLHeader

        #* \brief The point data.
        points: List[pcl.PointXYZRGBA, Eigen.aligned_allocator[pcl.PointXYZRGBA]]

        #* \brief The point cloud width (if organized as an image-structure).
        width: std.int = 0
        #* \brief The point cloud height (if organized as an image-structure).
        height: std.int = 0

        #* \brief True if no points are invalid (e.g., have NaN or Inf values in any of their floating point fields).
        is_dense: bool = True

        #* \brief Sensor acquisition pose (origin/translation).
        sensor_origin_: Eigen.Vector4f = Eigen.Vector4f.Zero ()
        #* \brief Sensor acquisition pose (rotation).
        sensor_orientation_: Eigen.Quaternionf = Eigen.Quaternionf.Identity ()


        # std container compatibility typedefs according to
        # http://en.cppreference.com/w/cpp/concept/Container

        # iterators
        @overload
        def begin(self) -> iterator:
            pass
        @overload
        def end(self) -> iterator:
            pass
        @overload
        def begin(self) -> const_iterator:
            pass
        @overload
        def end(self) -> const_iterator:
            pass
        def cbegin(self) -> const_iterator:
            pass
        def cend(self) -> const_iterator:
            pass
        @overload
        def rbegin(self) -> reverse_iterator:
            pass
        @overload
        def rend(self) -> reverse_iterator:
            pass
        @overload
        def rbegin(self) -> const_reverse_iterator:
            pass
        @overload
        def rend(self) -> const_reverse_iterator:
            pass
        def crbegin(self) -> const_reverse_iterator:
            pass
        def crend(self) -> const_reverse_iterator:
            pass

        #capacity
        def size(self) -> std.int:
            pass
        def max_size(self) -> index_t:
            pass
        def reserve(self, n: std.int) -> None:
            pass
        def empty(self) -> bool:
            pass
        @overload
        def data(self) -> PointXYZRGBA:
            pass
        @overload
        def data(self) -> PointXYZRGBA:
            pass

        @overload
        def resize(self, count: std.int) -> None:
            """*
                   * \brief Resizes the container to contain `count` elements
                   * \details
                   * * If the current size is greater than `count`, the pointcloud is reduced to its
                   * first `count` elements
                   * * If the current size is less than `count`, additional default-inserted points
                   * are appended
                   * \note This potentially breaks the organized structure of the cloud by setting
                   * the height to 1 IFF `width * height != count`!
                   * \param[in] count new size of the point cloud

            """
            pass

        @overload
        def resize(self, new_width: uindex_t, new_height: uindex_t) -> None:
            """*
                   * \brief Resizes the container to contain `new_width * new_height` elements
                   * \details
                   * * If the current size is greater than the requested size, the pointcloud
                   * is reduced to its first requested elements
                   * * If the current size is less then the requested size, additional
                   * default-inserted points are appended
                   * \param[in] new_width new width of the point cloud
                   * \param[in] new_height new height of the point cloud

            """
            pass

        @overload
        def resize(self, count: index_t, value: PointXYZRGBA) -> None:
            """*
                   * \brief Resizes the container to contain count elements
                   * \details
                   * * If the current size is greater than `count`, the pointcloud is reduced to its
                   * first `count` elements
                   * * If the current size is less than `count`, additional copies of `value` are
                   * appended
                   * \note This potentially breaks the organized structure of the cloud by setting
                   * the height to 1 IFF `width * height != count`!
                   * \param[in] count new size of the point cloud
                   * \param[in] value the value to initialize the new points with

            """
            pass

        @overload
        def resize(self, new_width: index_t, new_height: index_t, value: PointXYZRGBA) -> None:
            """*
                   * \brief Resizes the container to contain count elements
                   * \details
                   * * If the current size is greater then the requested size, the pointcloud
                   * is reduced to its first requested elements
                   * * If the current size is less then the requested size, additional
                   * default-inserted points are appended
                   * \param[in] new_width new width of the point cloud
                   * \param[in] new_height new height of the point cloud
                   * \param[in] value the value to initialize the new points with

            """
            pass

        #element access
        @overload
        def __getitem__(self, n: std.int) -> PointXYZRGBA:
            pass
        @overload
        def __getitem__(self, n: std.int) -> PointXYZRGBA:
            pass
        @overload
        def at(self, n: std.int) -> PointXYZRGBA:
            pass
        @overload
        def at(self, n: std.int) -> PointXYZRGBA:
            pass
        @overload
        def front(self) -> PointXYZRGBA:
            pass
        @overload
        def front(self) -> PointXYZRGBA:
            pass
        @overload
        def back(self) -> PointXYZRGBA:
            pass
        @overload
        def back(self) -> PointXYZRGBA:
            pass

        @overload
        def assign(self, count: index_t, value: PointXYZRGBA) -> None:
            """*
                   * \brief Replaces the points with `count` copies of `value`
                   * \note This breaks the organized structure of the cloud by setting the height to
                   * 1!
                   * \param[in] count new size of the point cloud
                   * \param[in] value value each point of the cloud should have

            """
            pass

        @overload
        def assign(self, new_width: index_t, new_height: index_t, value: PointXYZRGBA) -> None:
            """*
                   * \brief Replaces the points with `new_width * new_height` copies of `value`
                   * \param[in] new_width new width of the point cloud
                   * \param[in] new_height new height of the point cloud
                   * \param[in] value value each point of the cloud should have

            """
            pass



        @overload
        def assign(self, ilist: std.initializer_list[PointXYZRGBA]) -> None:
            """*
                   * \brief Replaces the points with the elements from the initializer list `ilist`
                   * \note This breaks the organized structure of the cloud by setting the height to
                   * 1!

            """
            pass

        @overload
        def assign(
            self,
            ilist: std.initializer_list[PointXYZRGBA],
            new_width: index_t
            ) -> None:
            """*
                   * \brief Replaces the points with the elements from the initializer list `ilist`
                   * \note This calculates the height based on size and width provided. This means
                   * the assignment happens even if the size is not perfectly divisible by width
                   * \param[in] ilist initializer list from which the points are copied
                   * \param[in] new_width new width of the point cloud

            """
            pass

        def push_back(self, pt: PointXYZRGBA) -> None:
            """* \brief Insert a new point in the cloud, at the end of the container.
                    * \note This breaks the organized structure of the cloud by setting the height to 1!
                    * \param[in] pt the point to insert

            """
            pass

        def transient_push_back(self, pt: PointXYZRGBA) -> None:
            """* \brief Insert a new point in the cloud, at the end of the container.
                    * \note This assumes the user would correct the width and height later on!
                    * \param[in] pt the point to insert

            """
            pass



        @overload
        def insert(self, position: iterator, pt: PointXYZRGBA) -> iterator:
            """* \brief Insert a new point in the cloud, given an iterator.
                    * \note This breaks the organized structure of the cloud by setting the height to 1!
                    * \param[in] position where to insert the point
                    * \param[in] pt the point to insert
                    * \return returns the new position iterator

            """
            pass

        @overload
        def transient_insert(self, position: iterator, pt: PointXYZRGBA) -> iterator:
            """* \brief Insert a new point in the cloud, given an iterator.
                    * \note This assumes the user would correct the width and height later on!
                    * \param[in] position where to insert the point
                    * \param[in] pt the point to insert
                    * \return returns the new position iterator

            """
            pass

        @overload
        def insert(self, position: iterator, n: std.int, pt: PointXYZRGBA) -> None:
            """* \brief Insert a new point in the cloud N times, given an iterator.
                    * \note This breaks the organized structure of the cloud by setting the height to 1!
                    * \param[in] position where to insert the point
                    * \param[in] n the number of times to insert the point
                    * \param[in] pt the point to insert

            """
            pass

        @overload
        def transient_insert(self, position: iterator, n: std.int, pt: PointXYZRGBA) -> None:
            """* \brief Insert a new point in the cloud N times, given an iterator.
                    * \note This assumes the user would correct the width and height later on!
                    * \param[in] position where to insert the point
                    * \param[in] n the number of times to insert the point
                    * \param[in] pt the point to insert

            """
            pass





        @overload
        def erase(self, position: iterator) -> iterator:
            """* \brief Erase a point in the cloud.
                    * \note This breaks the organized structure of the cloud by setting the height to 1!
                    * \param[in] position what data point to erase
                    * \return returns the new position iterator

            """
            pass

        @overload
        def transient_erase(self, position: iterator) -> iterator:
            """* \brief Erase a point in the cloud.
                    * \note This assumes the user would correct the width and height later on!
                    * \param[in] position what data point to erase
                    * \return returns the new position iterator

            """
            pass

        @overload
        def erase(self, first: iterator, last: iterator) -> iterator:
            """* \brief Erase a set of points given by a (first, last) iterator pair
                    * \note This breaks the organized structure of the cloud by setting the height to 1!
                    * \param[in] first where to start erasing points from
                    * \param[in] last where to stop erasing points from
                    * \return returns the new position iterator

            """
            pass

        @overload
        def transient_erase(self, first: iterator, last: iterator) -> iterator:
            """* \brief Erase a set of points given by a (first, last) iterator pair
                    * \note This assumes the user would correct the width and height later on!
                    * \param[in] first where to start erasing points from
                    * \param[in] last where to stop erasing points from
                    * \return returns the new position iterator

            """
            pass

        def swap(self, rhs: PointCloud[PointXYZRGBA]) -> None:
            """* \brief Swap a point cloud with another cloud.
                    * \param[in,out] rhs point cloud to swap this with

            """
            pass

        def clear(self) -> None:
            """* \brief Removes all points in a cloud and sets the width and height to 0."""
            pass

        def make_shared(self) -> Ptr:
            """* \brief Copy the cloud to the heap and return a smart pointer
                    * Note that deep copy is performed, so avoid using this function on non-empty clouds.
                    * The changes of the returned cloud are not mirrored back to this one.
                    * \return shared pointer to the copy of the cloud

            """
            pass

    #      </template specializations for class PointCloud>
    #  ------------------------------------------------------------------------



# </submodule pcl>
####################    </generated_from:point_cloud.h>    ####################

# </litgen_stub>
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
